name: Build and release

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow bleak asyncio screeninfo
          pip install nuitka imageio
      - name: Build application
        run: nuitka --standalone --enable-plugin=tk-inter --disable-console --include-data-dir=images=images --include-data-dir=settings=settings --windows-icon-from-ico=images/png/icon.png headphones_battery.py
      - name: Compress Application
        run: Compress-Archive ./headphones_battery.dist headphones_battery-${{ env.GITHUB_SHA:0:8 }}.zip
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GITHUB_SHA:0:8 }}
          release_name: Release ${{ env.GITHUB_SHA:0:8 }}
          draft: false
          prerelease: false
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: headphones_battery-${{ env.GITHUB_SHA:0:8 }}.zip
          path: headphones_battery/dist
